### ISSUE TITLE
Rotate y Axis name by default

### ISSUE THREAD

**Issue by akash-goswami** [akash-goswami/GridMap#1]
@AyanGhatak
Currently Y axis name is drawn horizontally, hence it takes unnecessary space. Rotate the Y Axis name vertically 90 degree by default. Add provision for the user to change it.

Check the `getForAxis` function in `stubs`. Add default rotation as 90.

**Comment by AyanGhatak** [comment]
@akash-goswami Have made a [PR](https://github.com/akash-goswami/GridMap/pull/2) on this. Please validate.
