### ISSUE TITLE
Axis name and label space management does not happen when the model is changed using predrawingHook

### ISSUE THREAD

**Issue by akash-goswami** [akash-goswami/GridMap#5]
@AyanGhatak 
For Y-Axis, if this data is given
   `label : { 
        preDrawingHook : function(d, i) { return d + '%%%%%%%'; },
	style: { }	
    }`

The chart does not shift right. This works fine when applied directly at dataset

**Comment by AyanGhatak** [comment]
@akash-goswami Hope [this](https://github.com/akash-goswami/GridMap/pull/6) works. Closing the issue.

**Comment by akash-goswami** [comment]
preDrawingHook getting called two times.
